### ISSUE TITLE
`git-branchless` is in nixpkgs

### ISSUE THREAD

**Issue by nh2** [msfjarvis/custom-nixpkgs#8]
Hi, I packaged `git-branchless` in nixpkgs:

https://github.com/NixOS/nixpkgs/pull/127971

Would you be up for joining as nixpkgs upstream co-maintainer there? Replacing your separate package at:

https://github.com/msfjarvis/custom-nixpkgs/blob/8bede036f14cfb6c2f45399675f32b88c9ae97ea/pkgs/git-branchless/default.nix

We should probably pull in your Darwin conditionals.

**Comment by msfjarvis** [comment]
Oh that's wonderful, I'll put up a PR for Darwin support sometime this week and include myself as a co-maintainer then.

**Comment by nh2** [comment]
Other packages are also in nixpkgs now. For example `helix`:

https://github.com/NixOS/nixpkgs/blob/1392ff98cc1f3e5fcb7c3a6b8c0c1be026f864f9/pkgs/applications/editors/helix/default.nix

([Yours here](https://github.com/msfjarvis/custom-nixpkgs/blob/8bede036f14cfb6c2f45399675f32b88c9ae97ea/pkgs/helix/default.nix).)

You might want to do a round of checking which ones are in by now -- I'm sure those ones would also appreciate you as co-maintainer!

`fclones` is not in nixpkgs yet but would be great to have!

**Comment by msfjarvis** [comment]
I've filed a PR in nixpkgs for Darwin support (https://github.com/NixOS/nixpkgs/pull/136287) and [removed git-branchless](https://msfjarvis.dev/g/custom-nixpkgs/fb41c0655dbe) from this repository.
